volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/data/wordpress"
      o: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/data/mariadb"
      o: bind

networks:
  network:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - network
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
